patrick-kidger/equinox

README.md, equinox/nn/__init__.py, equinox/nn/conv.py, tests/test_nn.py
I've really enjoyed learning about Equinox, and would love to be able to contribute!
Here's a first effort at adding convolutions (#1) - likely needs some fixes, and transposed convs need to be added.
It currently uses the workaround used by flax and haiku to handle non-batched inputs. Would be great if [https://github.com/google/jax/discussions/4092](url) is addressed so no hacks are required to make vmap work with convolutions.
=> Add convolutional layers

equinox/__init__.py, equinox/grad.py, tests/test_filter_grad.py
As the title, really.
Fixes #35.
=> Fixed `filter_grad(has_aux=True)` returning arguments in the wrong order.

equinox/__init__.py, equinox/grad.py, equinox/jit.py, equinox/module.py, tests/test_filter_jit.py
=> Fix function names when logging compilation progress

.pre-commit-config.yaml, docs/faq.md, equinox/nn/linear.py
=> Explain how to use higher-order tensors in Linear

README.md, docs/index.md, equinox/__init__.py, equinox/experimental/stateful.py, setup.py, tests/test_nn.py, tests/test_stateful.py
Bump version for next release.
=> Bump version

equinox/filters.py, tests/test_filters.py
=> Added `is_leaf` argument to `filter` and `partition`.

docs/requirements.txt
Bumped the version of `pymdown-extensions` to avoid `pygments` crashing (https://github.com/pygments/pygments/issues/2119, https://github.com/facelessuser/pymdown-extensions/pull/1666)
=> Fix pygments crashing

equinox/experimental/batch_norm.py, tests/test_nn.py
=> Batch norm grad crash fix

equinox/experimental/stateful.py
Fix for https://github.com/patrick-kidger/equinox/issues/163
=> added #outputs to the StateIndex example

equinox/serialisation.py, tests/test_serialisation.py
=> Fixed crash when serialising StateIndices without saved state

equinox/__init__.py, equinox/experimental/batch_norm.py, equinox/experimental/spectral_norm.py, equinox/experimental/stateful.py, equinox/serialisation.py, equinox/tree.py, tests/test_serialisation.py
=> Fixed BatchNorm not de/serialising correctly

equinox/experimental/stateful.py
Fixes https://github.com/patrick-kidger/equinox/issues/186#issuecomment-1235174078
=> Fixed `NotImplementedError` when computing gradients of `stateful` models

equinox/nn/rnn.py
When you see it... :)
Also made the docstring example more easily runnable.
=> Use bias (GRUCell)

equinox/callback.py, equinox/internal/__init__.py, equinox/internal/debug.py, equinox/internal/primitive.py, equinox/pretty_print.py, tests/test_noinline.py
- Partly revert `equinox.internal.hook_transform -> equinox.internal.announce_transform`.
- Fixed nitty filtered primitive stuff
=> Tweaks to `equinox.internal`

equinox/serialisation.py, tests/test_serialisation.py
As above. My use-case is to serialize/deserialize into `zipfile.ZipFile` sub-files which are available as file-like objects cannot be accessed by paths. I am not claiming this is the best possible implementation, treat it like a more constructive feature request :)
=> Allow passing file-like objects to eqx.serialise/deserialise

docs/faq.md, equinox/nn/composed.py
For https://github.com/patrick-kidger/equinox/issues/149#issuecomment-1328088282.
=> Added notes about 'TypeError: not a valid JAX type' to FAQ and nn.Lambda documentation.

docs/api/nn/activations.md, equinox/nn/__init__.py, equinox/nn/activations.py, mkdocs.yml, tests/test_nn.py
This PR adds PReLU activation function to equinox main package and corresponding docs. PR was created thanks to the advice from @patrick-kidger in the [Issue #247](https://github.com/patrick-kidger/equinox/issues/247).
=> feat: Add PReLU activaion

.pre-commit-config.yaml, examples/score_based_diffusion.ipynb, examples/unet.py
CC @Benjamin-Walker -- I thought I'd put this somewhere public so that it can be used.
=> Added U-Net example

equinox/module.py
=> `cls.__new__` -> `object.__new__` in `tree_unflatten`

equinox/nn/_dropout.py
=> Dropout now has a stop_gradient on p

equinox/_compile_utils.py, equinox/_jit.py, equinox/_pretty_print.py, equinox/_vmap_pmap.py, tests/test_jit.py, tests/test_pmap.py
=> `.lower().compile()(...)` now performs filtering on input

equinox/_custom_types.py, equinox/nn/_normalisation.py
=> LayerNorm and GroupNorm now have API compatibility with BatchNorm

equinox/_ad.py, equinox/internal/_loop/loop.py, tests/test_ad.py
- Crash fix for using `filter_custom_jvp` with integer-valued matrices. (Due to JAX issue https://github.com/google/jax/issues/16000)
- Added `buffers` and `checkpoints` arguments to `eqxi.scan`.
=> Better loop

equinox/internal/_loop/checkpointed.py
Checkpointed while loop now traces the body_fun only once in the backward pass. The net result is a faster compile time, but a slightly slower runtime, I think.
Need to benchmark this further.
=> Possibly more efficient while loop?

equinox/_module.py, equinox/internal/_errors.py, tests/test_module.py
- Fixed a docstring
- Added support for flattening with keypaths.
=> Added flattening with key paths

equinox/nn/_composed.py, tests/test_nn.py
Closes #290 
@patrick-kidger   Follows your suggested naming convention.  Please tell me if there is anything else I should add.
=> Add support for bias to MLP

equinox/_ad.py, equinox/internal/_loop/common.py, tests/test_ad.py
Fix for #411.
Also fixes a GPU slowdown.
=> Fixes galore

equinox/_doc_utils.py, equinox/_pretty_print.py, equinox/internal/__init__.py, equinox/internal/_debug.py, equinox/internal/_loop/bounded.py, equinox/internal/_loop/checkpointed.py, equinox/internal/_loop/common.py, equinox/internal/_loop/loop.py, tests/requirements.txt, tests/test_debug.py, tests/test_onnx.py, tests/test_while_loop.py
- Added `equinox.internal.check_dce`
- added several fastpaths for checkpointed while loop
=> Added several speed improvements for CWL with all checkpoints

equinox/internal/_loop/common.py
(and Lineax and Diffrax tests failing as a result :D)
=> Fix for while_loop being initialised wrong

equinox/internal/_nextafter.py, tests/test_errors.py
This is getting removed from NumPy, and thus also jax.numpy.
=> NINF -> -inf

equinox/_module.py
It's quite common for its input to be a PyTree, but custom PyTrees might not have an __eq__ method registered. See https://github.com/patrick-kidger/diffrax/issues/287
=> Static now flattens its input.

equinox/nn/_activations.py, equinox/nn/_attention.py, equinox/nn/_batch_norm.py, equinox/nn/_composed.py, equinox/nn/_conv.py, equinox/nn/_dropout.py, equinox/nn/_embedding.py, equinox/nn/_linear.py, equinox/nn/_normalisation.py, equinox/nn/_pool.py, equinox/nn/_rnn.py, equinox/nn/_spectral_norm.py
This PR resolves #461 and implements the requested feature of having named scopes for better profiling and debugging.
=> Added named_scope to all nn modules

equinox/nn/_normalisation.py
(dlwh pointed out that otherwise this can silently normalise over sequence dimensions in transformer models if you miss the vmap)
=> LayerNorm is now a bit safer, by explicitly validating shapes.

.pre-commit-config.yaml, equinox/internal/__init__.py, equinox/internal/_closure_to_pytree.py, tests/requirements.txt, tests/test_closure_to_pytree.py
Added equinox.internal.closure_to_pytree
=> closure to pytree

equinox/_jit.py, equinox/_module.py, tests/test_enum.py, tests/test_errors.py, tests/test_module.py
=> Bound methods now support equality against each other.

docs/api/filtering/transformations.md, equinox/__init__.py, equinox/_ad.py, tests/test_checkpoint.py
=> add `filter_checkpoint`

docs/faq.md
(The failing CI is unrelated, due to an upstream failure in jaxlib==0.4.16. This will be fixed in the next jaxlib release.)
=> Added FAQ entries comparing against PyTorch etc.

equinox/_better_abstract.py
When subclassing, it used to be the case that `cls.__abstractvars__`
basically never got smaller (only if an element was overriden by a
class-level attribute or method):
```python
class Foo(eqx.Module):
x: AbstractVar[bool]
class Bar(eqx.Module):
x: bool
Bar.__abstractvars__ == frozenset({"x"})
```
This was intended -- the idea is that the all abstractvars would get
checked during initialisation, i.e. validity wrt this condition being
a property of the instance, rather than being a property of just the
class object.
With this change, the above example will remove `x` from
`__abstractvars__`.
This is because it's useful and typical to reason about whether a class
is abstract or not -- it's much more annoying to have to reason about
whether each individual instance is abstract. Indeed the …
=> AbstractVars are now overriden by annotations in subclasses.

equinox/_better_abstract.py, equinox/_module.py, tests/test_abstract.py
The new implementation is also a fair bit simpler.
=> Fixed Abstract{Class,}Var misbehaving around multiple inheritance.

docs/api/debug.md, equinox/_ad.py, equinox/_errors.py, equinox/_tree.py, equinox/debug/__init__.py, equinox/debug/_dce.py, equinox/debug/_max_traces.py, equinox/internal/__init__.py, equinox/internal/_getkey.py, tests/conftest.py, tests/helpers.py, tests/test_ad.py, tests/test_callback.py, tests/test_debug.py, tests/test_enum.py, tests/test_finalise_jaxpr.py, tests/test_jit.py, tests/test_misc.py, tests/test_module.py, tests/test_noinline.py, tests/test_nontraceable.py, tests/test_pmap.py, tests/test_primitive.py, tests/test_scan.py, tests/test_tree.py, tests/test_vmap.py, tests/test_while_loop.py
- Added trace counting debug tools.
- Tidied up error docs.
- eqx.debug.store_dce now supports non-arrays
- Enhanced tree_equal to be able to perform shaped_allclose-type functionality.
- Better warnings
- Move GetKey into eqxi (to avoid duplication in downstream libraries).
=> Debug and testing improvements

docs/tricks.md
Copy of #581 without the extra commit.
Credit to @homerjed for spotting this!
=> Fix missing shape specification

equinox/_misc.py, equinox/nn/_batch_norm.py, equinox/nn/_stateful.py
=> Better default behaviour for BN dtypes; better State errors.

equinox/nn/_batch_norm.py, equinox/nn/_spectral_norm.py
=> Fixed wrong PRNGKey annotation.

equinox/internal/_loop/common.py, equinox/nn/_activations.py, equinox/nn/_attention.py, equinox/nn/_conv.py, equinox/nn/_pool.py, tests/conftest.py, tests/test_ad.py, tests/test_closure_to_pytree.py, tests/test_debug.py, tests/test_make_jaxpr.py, tests/test_nn.py, tests/test_pmap.py, tests/test_while_loop.py
- Now using strict rank and dtype promotions when testing.
- eqxi.while_loop now has better error messages for mismatched structures
=> Strict testing + better errors for eqxi.while_loop

equinox/_jit.py, tests/test_jit.py
=> Fix AOT compilation for eqx.filter_jit with kwargs

equinox/_serialisation.py, tests/test_serialisation.py
=> Deserialisation now works with filter_eval_shape

equinox/internal/_loop/checkpointed.py
This is to fix a crash on TPUs, see #628.
=> Removed runtime errors from eqxi.while_loop.

equinox/nn/_conv.py
Tagging @ChenAo-Phys as I think I've bumped into a bug.
I've added an assert statement that when `padding='SAME'/'SAME_LOWER'`, the input and output spatial dimensions should be the same. This causes a couple of tests to fail. It looks like the combination of `padding='SAME'/'SAME_LOWER'` with `padding_mode != 'ZEROS'` and `stride > 1` does not produce the right amount of padding.
This PR:
- Adds these now-failing assert statements.
- Refactors some docstrings (primarily so that they render correctly in the online docs).
- Switches the order of `jnp.expand_dims(x, axis=0)` and `self._nonzero_pad`, so that the unsqueezing/squeezing happens directly either side of the convolution. This is just for cleaner readability, really. I've checked that this is unrelated to the failing asserts.
Do …
=> Tweaked new `Conv` and `ConvTranspose` padding options

equinox/_module.py, tests/test_module.py
=> Now emits a warning if you're about to silently footgun yourself by assigning a jax-transformed layer.

docs/all-of-equinox.md
=> minor grammar fix in all-of-equinox.md

examples/mistral_7b.md, mkdocs.yml
CC @AakashKumarNain !
(Very happy to include more details on this page if there's anything you think is better stated here rather than in your own README.)
=> Added Mistral 7B example

equinox/nn/_conv.py
Addresses https://github.com/patrick-kidger/equinox/issues/728
=> Add docstring about CNN transposing

examples/score_based_diffusion.ipynb
:smile:  
PS: pattern.md is commented in the mkdocs.yml and it raises an error
=> Fix a broken link in the docs

docs/faq.md
Scaning over modules has come up a lot and the threads see enough traction that it seems worthwhile to put in FAQ (or if you ever want to just add them to equinox itself I can do that too). 
Relevant issues: https://github.com/patrick-kidger/equinox/issues/446, https://github.com/patrick-kidger/equinox/issues/630, https://github.com/patrick-kidger/equinox/issues/709, https://github.com/patrick-kidger/equinox/issues/558
=> Add scan over module faq

examples/score_based_diffusion.ipynb
fixes https://github.com/patrick-kidger/equinox/issues/748
=> Fix einops

equinox/internal/_loop/checkpointed.py
This was quite the obscure issue! This occurs when:
- using a checkpointed while loop
- with a body function that has a closed-over tracer
- and that closed-over tracer is differentiated
- and there are no other closed-over tracers that are differentiated
- and the dependency on that tracer is only linear.
In this case then Equinox croaks and dies.
Or at least it did. Not any more!
=> Fixes edge-case crash with CWL

equinox/internal/_noinline.py
=> Removed use of deprecated jax.core.pp_*

equinox/internal/_loop/checkpointed.py
=> Fix for a case where we're hashing tracers.

equinox/internal/_primitive.py
In particular this resulted in a trace error here: https://github.com/patrick-kidger/lineax/issues/101
=> Fix missing `out_axes` for transpose-of-vprim.

equinox/_tree.py, tests/test_tree.py
Fix for https://github.com/patrick-kidger/equinox/issues/818.
=> Make _DinstinctTuple inherit from tuple

equinox/_jit.py
=> Add `_FilteredStderr.flush`.

equinox/_jit.py, tests/test_errors.py
=> Now filtering pure_callback's messages via logs rather than at stderr.

equinox/_ad.py, equinox/_pretty_print.py, tests/test_pformat.py
Possible fix for #854, let's see if tests pass.
=> Hopefully compatibility with JAX 0.4.32

.pre-commit-config.yaml, equinox/_jit.py
Fixes https://github.com/patrick-kidger/diffrax/issues/506
=> JAX 0.4.33 changes how errors work, which broke the nice error_if messages. Hopefully this should be cross-version compatible.

equinox/internal/_primitive.py, equinox/nn/_activations.py, equinox/nn/_attention.py, equinox/nn/_batch_norm.py, equinox/nn/_conv.py, equinox/nn/_dropout.py, equinox/nn/_embedding.py, equinox/nn/_linear.py, equinox/nn/_misc.py, equinox/nn/_mlp.py, equinox/nn/_normalisation.py, equinox/nn/_pool.py, equinox/nn/_rnn.py, equinox/nn/_sequential.py, equinox/nn/_spectral_norm.py, equinox/nn/_weight_norm.py, pyproject.toml
=> New version fixes

equinox/_module.py, tests/test_module.py
The alternative was starting to get far too hairy -- lots of threading the needle try to make both https://github.com/patrick-kidger/equinox/issues/969 and https://github.com/patrick-kidger/equinox/issues/832 work simultaneously.
Fixes #969
=> Conversion now runs after both __init__ and __post_init__.

equinox/_errors.py, equinox/_jit.py
Inspired by https://github.com/patrick-kidger/equinox/pull/976 we now filter the traceback outside of JIT rather than inside of tracing.
@ZagButNoZig: very much inspired by your implementation: I realised we could simplify it in a few ways (save just one traceback) and fixed a bug (`jit_wrapper` could be repeated so I instead use a UUID as a stack marker.) WDYT?
=> `eqx.filter_jit` should now be faster as it doesn't do an inside-JIT check each time

mkdocs.yml
=> Unbreak search!

equinox/_module.py, tests/test_module.py
=> Fix round trip flattening + pickling

README.md, docs/awesome-list.md, docs/index.md
=> docs: add diffraxtra

equinox/_module.py
A followup to #994.
AFAICT there's no performance impact, just a cleaner definition.
Still in draft mode because I'm trying to see if there's a way to add speed ups, e.g. define the un/flattening in C++ or whatnot. Seems a separate-enough discussion from #994.
=> refactor: collect Module (un)flattening

docs/awesome-list.md
ksim is a robotics RL simulation library for open-source community built with Equinox.
=> add ksim to the list

docs/awesome-list.md
Hi Patrick,
Adding ESM-C as requested! I also shamelessly slipped in joltz and boltz-binder-design -- can remove these if you like 
Nick
=> add esmj (and joltz and boltz-binder-design :) ) to awesome-list.md

docs/awesome-list.md
Adding the [nequip-eqx](https://github.com/teddykoker/nequip-eqx) implementation.
=> Add project to awesome-list.md

equinox/_errors.py
=> Update EQX_ON_ERROR=breakpoint under vmap and new JAX

equinox/_tree.py, equinox/nn/_inference.py
=> chore(docs): improve `tree_at` documentation

docs/awesome-list.md
As discussed in https://github.com/patrick-kidger/optimistix/issues/166#issuecomment-3288865860, add the [Mutax](https://github.com/gerlero/mutax) library to the list
=> Add Mutax to awesome list

tests/conftest.py, tests/test_pmap.py, tests/test_sharding.py, tests/test_while_loop.py
C.f. https://github.com/patrick-kidger/equinox/pull/1078#issuecomment-3312780896 @mjo22
=> Enable sharding tests

.github/workflows/release.yml, .github/workflows/run_tests.yml, CONTRIBUTING.md, pyproject.toml, tests/requirements.txt
Also bumped doc stack to bugfixed versions.
=> Updated to use optional-dependencies throughout.
