patrick-kidger/equinox

README.md
equinox/gradf.py
equinox/update.py
examples/train_mlp.py
tests/test_gradf.py
tests/test_update.py

Currently, `gradf` returns `0` for non-trainable parameters. A better approach is to return `None` instead.

make gradf return None for non-trainable parameters

---

README.md
equinox/__init__.py
equinox/filters.py
equinox/gradf.py
equinox/module.py
examples/modules_to_initapply.py
tests/test_filters.py

- Added `split` and `merge` to the public interface.
- It is now valid to annotate Module attributes with `dataclasses.field(init=False)`.
- Added example on how to use Equinox in an init/apply manner.

version 0.0.2

---

README.md
equinox/__init__.py
equinox/filters.py
tests/test_filters.py

- Added `is_array` and `is_inexact_array_like`.
- Tweaked the behaviour of `is_array_like` to use an instance check rather than doing a try/except on `jnp.asarray`. This is much (much) faster. Technically this is a slight change in behaviour (wrt arguments like `[1.0]`), but as its primary use is filtering, and always called on leaves, this (hopefully) shouldn't be an issue.

Updated array filters

---

examples/frozen_layer.py
examples/train_mlp.py

Replaced `depth` with `width_size` in `train_mlp.py` and `frozen_layer.py` examples

fix minor variable mix up in examples

---

README.md
equinox/__init__.py
equinox/gradf.py
equinox/jitf.py
equinox/module.py
equinox/nn/composed.py
equinox/nn/dropout.py
equinox/nn/linear.py
equinox/nn/rnn.py
examples/filtered_transformations.py
examples/frozen_layer.py
examples/train_rnn.py
tests/test_filter_jit.py
tests/test_module.py

**More important points**
- `filter_jit` and `filter_grad` and `filter_value_and_grad` now have a sensible default for `filter_spec`. This means it is now typical to simply write
```python
@eqx.filter_jit
@eqx.filter_grad
def loss(model, data):
...
```
- Moreover, as 99% of all uses cases are to JIT wrt all JAX arrays and differentiate all floating point JAX arrays, then this makes `filter_jit` and `filter_grad` pretty much just upgraded versions of `jax.jit` and `jax.grad`, suitable for all use-cases.
- `filter_jit` is now smart enough to filter its return types (as well as its arguments). This means that PyTrees with mixed dynamic/static pieces can be returned without issue.
- Previously `filter_jit` behaved like `jax.jit`: (a) implicitly casting int/float/bool/complex to a JAX array, …

Version 0.1.1

---

equinox/nn/conv.py
tests/test_nn.py

@andyehrenberg I think I've got transposed convolutions sorted out.
WDYT? If you're happy with this then I'll merge this in to the other ongoing feature branch.
The main references I used to implement this were Relation 14 of [this reference](https://arxiv.org/abs/1603.07285) and [these](https://github.com/vdumoulin/conv_arithmetic/blob/af6f818b0bb396c26da79899554682a8a499101d/README.md#transposed-convolution-animations) animations.

Tidied; simplified; generalised ConvTranspose implementation.

---

docs/api/utilities.md
equinox/__init__.py
equinox/module.py
equinox/tree.py

More generally, this adds pretty-printing for all PyTrees containing JAX arrays, via the `equinox.tree_pformat` function. This is used in `equinox.Module.__str__`.
- Note that this will produce best results for Python >3.10, for which the standard library `pprint` supports dataclasses. On lower versions of Python it won't add line breaks.
- Note that we deliberately only set `equinox.Module.__str__` and not `equinox.Module.__repr__`, so as to avoid an infinite recursion: `pprint` uses an object's `__repr__`.

Added pretty-printing for Modules

---

equinox/nn/attention.py
tests/test_nn.py

Following up on the conversation in https://github.com/patrick-kidger/equinox/pull/38#discussion_r842082571, this is probably a better default for modelling. Moreover it's a more consistent default.
This should be merged in the next breaking release.

Remove default bias in `MultiheadAttention`

---

equinox/experimental/batch_norm.py
equinox/experimental/spectral_norm.py
equinox/experimental/stateful.py
equinox/jit.py
tests/test_stateful.py

- Refactor + Feature: `StateIndex(inference=True)` has been optimised substantially. It now inputs the state as an argument into the JIT region at runtime, rather than dynamically via a `host_callback.call` at call time. In particular it does not bake in the value at trace-time, as otherwise subsequent updates to the state will not be seen. (This makes the implementation pretty complicated.)
- Performance improvement + Bugfix: `BatchNorm`, `SpectralNorm` now pass `__init__(inference=...)` on to the `StateIndex`s they contain. Basically this is a minor bugfix, that should improve the performance of these operations at inference.
- Feature: added `filter_jit(...).lower(...)`. (Used in the tests for the above.)

Improvements to stateful

---

equinox/__init__.py
equinox/module.py
equinox/pretty_print.py
equinox/tree.py
tests/test_pformat.py

Switched from using the builtin `pprint` library to using `jax._src.pretting_printing`, which is a much better pretty-printer. In particular the `__str__` representation of an `equinox.Module` should generally be narrower now.

Improved pretty-printing

---

docs/api/filtering/filtered-transformations.md
docs/api/helpers.md
docs/api/stateful.md
docs/faq.md
docs/requirements.txt
equinox/__init__.py
equinox/compile_utils.py
equinox/custom_types.py
equinox/doc_utils.py
equinox/experimental/__init__.py
equinox/experimental/batch_norm.py
equinox/experimental/stateful.py
equinox/experimental/vmap_pmap.py
equinox/filters.py
equinox/grad.py
equinox/jit.py
equinox/module.py
equinox/nn/attention.py
equinox/pretty_print.py
equinox/tree.py
equinox/vmap_pmap.py
tests/helpers.py
tests/test_filter_grad.py
tests/test_filter_jit.py
tests/test_filter_pmap.py
tests/test_filter_vmap.py
tests/test_filters.py
tests/test_nn.py
tests/test_stateful.py
tests/test_tree.py

This is a big one.
- **Feature**: Added `eqx.filter_vmap` and `eqx.filter_pmap`. Closes #65.
- Yay, we're rounding out our collection of filtered transformations.
- **Feature**: Prevented unnecessary recompilation in some edge cases like calling `filter_jit(filter_grad(...))` twice, i.e. when materialising a new gradient function twice. See https://github.com/google/jax/discussions/10284; in particular we do it by using appropriately-structured PyTrees rather than caching, which is good.
- **Feature**: Added `eqx.tree_inference` as a convenience.
- **Refactor**: Improved the interface to `filter_{jit,grad,value_and_grad}`:
- Supports optional currying (a plain `@eqx.filter_jit` will still work):
```python
@eqx.filter_jit(default=...)
def f(...):
...
```
- A much neater way of specifying …

Improved filtered transformations

---

equinox/custom_types.py
equinox/doc_utils.py
equinox/tree.py
tests/test_tree.py

Closes #47.
- Can now substitute arbitrary nodes, not just leaves
- These substituted nodes can now have different structures to each other.
- Will raise an error if `where` depends on the values of the leaves of the PyTree.
In addition, `tree_equal` should now work under JIT.

Improved `tree_at`

---

docs/api/nn/pool.md
equinox/nn/__init__.py
equinox/nn/pool.py
mkdocs.yml
tests/test_nn.py

I currently use einops.rearrange so that the pooling layers and conv layers take the same tensor format as input, BCHW. For some reason lax.conv_general_dilated and lax.reduce_window are BCHW and BHWC respectively. Can do this not using einops if you would prefer to not have the extra dependency.

Added max and avg pool, alongside tests and docs

---

CONTRIBUTING.md
equinox/nn/pool.py

This link in the `eqx.nn.Pooling` docstring was broken, and then I stumbled on a small typo in the contrib docs while fixing that

fix two small typos in documentation

---

equinox/nn/conv.py
tests/test_nn.py

As in the title: your implementation of `eqx.nn.Conv` doesn't expose the ability to subdivide feature channels into groups. This PR implements that feature.

Implement num_feature_groups for Conv

---

equinox/vmap_pmap.py
tests/test_filter_pmap.py
tests/test_filter_vmap.py

Partially addresses https://github.com/patrick-kidger/equinox/issues/115 by fixing a bug in filter_vmap to allow using a pytree as filter spec for the out parameter of filter_vmap. Adding tests for this case for both p- and vmap, just in case :)
Recreating this PR because with the previous I managed to introduce a merge conflict with myself...

Fix vmap with pytree out

---

equinox/experimental/batch_norm.py

They don't have to be just strings. (Common misconception that I fell afoul of as well.)

Allow hashable axis names

---

.github/workflows/run_tests.yml
docs/api/filtering/filtered-transformations.md
equinox/__init__.py
equinox/compile_utils.py
equinox/eval_shape.py
equinox/jit.py
equinox/vmap_pmap.py
tests/test_eval_shape.py
tests/test_filter_jit.py
tests/test_filter_pmap.py

1. Previously using a callable `out` parameter was experimental for
`filter_vmap` -- because it monkey-patched JAX internals -- and
unavailable for `filter_pmap`. It has now been updated to work for both,
and using only the public JAX API. (Hurrah.)
2. Drive-by: Added `eqx.filter_eval_shape` as it looked like this was
going to useful as part of implementing the previous feature. In the
end this wasn't the case, but we get a new feature anyway.
3. Drive-by: Fixed a crash bug when filter-jit'ing a partial-wrapped
function whilst using a PyTree as its filter spec (`fn`).
Closes #115.
CC @jatentaki WDYT?

eqx.filter_{vmap,pmap}(out=...) not experimental

---

docs/api/nn/pool.md
equinox/nn/__init__.py
equinox/nn/pool.py
tests/test_nn.py

Just noticed this minor issue. CC @paganpasta for interest.

`{Avg,Max}Pool{1,2,3}D` -> `{Avg,Max}Pool{1,2,3}d`. Removed wrong stride default.

---

equinox/nn/normalisation.py
tests/test_nn.py

- Removes erroneous `shape` parameter from docstring
- Fixes #127 
- Adds tests for various argument combinations

Fix GroupNorm channels argument and docstring

---

equinox/nn/composed.py
tests/test_nn.py

- Implements #152 
- Adds indexing tests for `Sequential`

make `Sequential` indexable and add tests

---

equinox/nn/composed.py
tests/test_nn.py

Adds the `__len__` and `__iter__` methods to `eqx.nn.Sequential`
It isn't that hard to write `len(seq.layers)` or `zip(seq.layers, ...)`, but this does make it just slightly cleaner and also mimics the behavior of pytorch Sequential module.

Add len and iter methods to nn.Sequential

---

equinox/nn/attention.py
tests/test_nn.py

Adds `dot_product_attention_weights` and `dot_product_attention` functions and tests
**Design considerations**:
- `dot_product_attention` and `dot_product_attention_weights` don't take multi-head inputs -- instead attention heads are vmap'd over in `MultiheadAttention`. This allows for greater flexibility when creating other types of attention modules
- To simplify the `dot_product_attention` signature -- `dropout_fn` is added as a single argument callable, which should close over the dropout arguments like `key` and `inference`. The alternative I think would be to add a functional version of dropout and add its arguments to `dot_product_attention`, however this would make changing the dropout rate after initializing the module less intuitive -- since dropout rate would have to be an …

Add attention functions and tests

---

equinox/nn/pool.py
tests/test_nn.py

Corresponding issue: https://github.com/patrick-kidger/equinox/issues/175
- Added `use_ceil` parameter to `Pool`
- Added a check to make sure garbage values are not pooled if `padding > kernel/2`.

added use_ceil to pooling

---

equinox/__init__.py
equinox/nn/attention.py
tests/test_nn.py

https://github.com/patrick-kidger/equinox/blob/18d260d4abab92b6853f2bdbd8335fe2ec316416/equinox/nn/attention.py#L221-L223
https://github.com/patrick-kidger/equinox/blob/18d260d4abab92b6853f2bdbd8335fe2ec316416/equinox/nn/attention.py#L265-L267
The right axis for mask to map over is the first axis, so pass mask as keyword to make it map over axis index 0.

fix attention with mask and add tests

---

equinox/nn/composed.py

As discussed in #182 
- Changes Sequential `layers` attribute to be tuple to enforce immutability of equinox modules.
- Constructor can still take any `Sequence` type

make sequential module immutable

---

equinox/nn/conv.py
tests/test_nn.py

- Adds asymmetric padding to convolutions. The asymmetric padding is defined as a `Sequence` of `int` of length `2 * num_spatial_dim`, analog to `torch.nn.functional.pad`.

Add support for asymmetric padding in Conv and ConvTransposed.

---

MANIFEST.in
docs/all-of-equinox.md
equinox/__init__.py
equinox/filters.py
setup.py
tests/test_filter_grad.py
tests/test_filters.py

Likewise for `is_inexact_array`.
This is motivated by two main use-cases:
- Passing NumPy arrays as the data to a JIT'd model: in practice it's common to have your data pipeline use NumPy arrays. (It certainly shouldn't use JAX arrays, since those can't be sliced etc.) It'd be convenient to be able to pass these into a JIT'd `make_step` function without needing to change the defaults.
- `JAX_DEBUG_NANS=1` will re-run your code using NumPy arrays rather than JAX arrays. We should generally behave the same irrespective of this distinction.

`is_array` now returns True for NumPy arrays

---

equinox/vmap_pmap.py
tests/test_filter_jit.py
tests/test_filter_pmap.py

At the moment, `filter_vmap` traces its input function to determine the shape of its outputs, so that it can handle `out_axes` correctly.
After this change, its wrapped `jax.vmap` will instead output all arrays with batch axis 0, and then have the batch axis swapped afterwards if necessary.
This mean we can elide the extra tracing call, which reduces compile time.

Removed extra tracing call made by filter_vmap

---

equinox/tree.py

https://github.com/patrick-kidger/equinox/blob/253522cd23b0522e57088d4c886a753b2594e0d7/equinox/tree.py#L259-L260
https://github.com/patrick-kidger/equinox/blob/253522cd23b0522e57088d4c886a753b2594e0d7/equinox/tree.py#L268-L269
The `out.extend` inside the for loop of `out` will cause the same node to be added many times. 
For example:
```python
import time
class Model(eqx.Module):
sub_module: eqx.Module
inference: bool
def __init__(self, sub_module):
self.sub_module=sub_module
self.inference=False
model = Model(None)
for i in range(11):
model = Model(model)
now = time.time()
eqx.tree_inference(model, True)
print(time.time()-now) # 5s+
def _inferences(pytree):
out = eqx.tree._inferences(pytree)
print(len(out), len(set(out))) # 82500 12
return out …
```

fix tree_inference

---

README.md
equinox/internal/__init__.py
equinox/internal/ad.py
equinox/internal/debug.py
equinox/internal/errors.py
equinox/internal/finalise_jaxpr.py
equinox/internal/noinline.py
equinox/internal/nontraceable.py
equinox/internal/onnx.py
equinox/internal/unvmap.py
equinox/jit.py
equinox/nn/linear.py
setup.py
tests/helpers.py
tests/requirements.txt
tests/test_finalise_jaxpr.py
tests/test_jit.py
tests/test_onnx.py
tests/test_pformat.py
tests/test_stateful.py

New features:
- `equinox.internal.to_onnx` for export to ONNX.
- `equinox.internal.{finalise_jaxpr,finalise_fn,finalise_eval_jaxpr,finalise_jaxpr_as_fun}`. The main one here is `finalise_jaxpr`, which is essentially a jaxpr-to-jaxpr transformation that rewrites all custom primitives in terms of their `impl` rule. This is useful prior to ONNX export: this can be the final transformation applied to a jaxpr, so that it is now written in terms of primitives that have ONNX export rules. (But naturally this will break anything further jaxpr processing via vmap/grad/etc.)
- `equinox.internal.nontraceable` is an operation that cannot be vmap'd, grad'd etc. (Useful to check that there were no closed-over tracers at the end of a final-style higher order primitive.)

Added ONNX export; finalise_jaxpr, nontraceable

---

equinox/nn/attention.py
tests/test_nn.py

Handled the argument, added a warning and 2 simple test cases, all similar to how Dropout does it
Relates: #287

Fixed deterministic=True being ignored in MultiheadAttention

---

equinox/nn/_composed.py

It's not immediately clear what convention `depth` is using. For example, a depth two network could either correspond to a network of shape: (in layer, hidden layer 1, hidden layer 2, output layer) or of shape (in layer, hidden layer, output layer). This makes it clear exactly which convention equinox uses.

Make `depth` more explicit

---

equinox/nn/_conv.py

Simple change to address https://github.com/patrick-kidger/equinox/issues/308. Previously the code in the issue would result in 
```
ValueError: Operands could not be broadcast together for add on shapes (1, 4, 8) (4, 1) and with the config option jax_numpy_rank_promotion='raise'. For more information, see https://jax.readthedocs.io/en/latest/rank_promotion_warning.html.
```
Now it results in 
```
Array([[ 0.7041937 ,  0.7041937 ,  0.7041937 ,  0.7041937 ,  0.7041937 ,
0.7041937 ,  0.7041937 ,  0.7041937 ],
[-0.42025453, -0.42025453, -0.42025453, -0.42025453, -0.42025453,
-0.42025453, -0.42025453, -0.42025453],
[ 0.25013918,  0.25013918,  0.25013918,  0.25013918,  0.25013918,
0.25013918,  0.25013918,  0.25013918],
[ 0.36006033,  0.36006033,  0.36006033,  0.36006033,  0.36006033, …
```

Remove implicit promotion in Conv

---

equinox/nn/_normalisation.py
tests/test_nn.py

Addresses https://github.com/patrick-kidger/equinox/issues/310. I handled the deprecation of `elementwise_affine` in as similar a manner as I could to `dropout` which also has a deprecated argument.

Change LayerNorm to allow weights or biases

---

equinox/experimental/_batch_norm.py
equinox/nn/_normalisation.py

Hi Patrick,
I encountered some numerical instability in training with `LayerNorm` as losses return `NaN`. When turning on `jax_debug_nans`, it showed that `LayerNorm` failed to compute `jax.lax.rsqrt`.
I refer to Flax about this issue. That is, it is better to clip variance (this [line](https://github.com/google/flax/blob/660fd6c16df3a5fa2b5b0c2eaf9e2ca4de40bea4/flax/linen/normalization.py#L101)) to enable numerical stability for float32.
I don't have a certain test case for this.

Clip variance in normalization

---

equinox/nn/_conv.py

Very simple change analogous to #311 but for `ConvTranspose` instead of `Conv`. Secondary fix to #308.

Remove implicit rank promotion in ConvTranspose

---

equinox/nn/_composed.py

Fixes a few minor typos in #358.

Fix docstring typos in `MLP.__init__`

---

equinox/_ad.py
equinox/_jit.py
equinox/_make_jaxpr.py
equinox/_module.py
equinox/_vmap_pmap.py
equinox/internal/_noinline.py
tests/test_module.py

Otherwise this places a dynamic node in the static metadata, which wreaks all kind of havoc.
Fixes #377.

module_update_wrapper no longer assigns __wrapped__

---

equinox/internal/_loop/common.py

Adds syntactic sugar for add, mul, divide, and power when updating buffers at an index so that we may use `buffer.at[index].add(foo)` instead of `buffer.at[index].set(buffer[index] + foo)`.

Extended `buffer.at[index].set(...)` to include `buffer.at[index].add(...)`

---

docs/api/advanced_fields.md
docs/api/utilities/miscellaneous.md
equinox/__init__.py
equinox/_better_abstract.py
equinox/_module.py
equinox/nn/_composed.py
examples/bert.ipynb
mkdocs.yml
tests/test_module.py

This adds `eqx.field(converter=...)`, for calling a function on a field at the end of `__init__`.
For consistency `eqx.static_field`, is now deprecated in favour of `eqx.field(static=True)`. (But `static_field` will continue to exist for backward compatibility.)
`equinox.{AbstractVar, AbstractClassVar}` are also added to the public API.

Added support for converting a field

---

README.md
docs/index.md
equinox/_ad.py
equinox/internal/__init__.py
equinox/internal/_debug.py
equinox/internal/_finalise_jaxpr.py
equinox/internal/_loop/__init__.py
equinox/internal/_loop/bounded.py
equinox/internal/_loop/checkpointed.py
equinox/internal/_loop/common.py
equinox/internal/_loop/loop.py
pyproject.toml
tests/test_ad.py
tests/test_debug.py
tests/test_while_loop.py

- Now using symbolic zeros in `filter_custom_{jvp,vjp}`. This also brings with it an API tweak for backward compatibility. (E.g. `filter_custom_jvp.defjvp -> filter_custom_jvp.def_jvp` for the new behaviour.)
- Removed unnecessary `lax.select` in `eqxi.while_loop` when not vmap'ing. This should improve speed slightly when not vmap'ing.
- Improved speed of backprop through `eqxi.while_loop` buffers, in particular avoiding https://github.com/google/jax/issues/10197. In particular this can be used to reduce some programs with quadratic runtime down to just linear runtime.

better custom autodiff

---

equinox/_module.py

Methods of `equinox.Module` lose their `__doc__`, `__name__`, `__module__`, etc.
The methods all get wrapped with`jax.treel_util.Partial`, which doesn't use `functools.wraps` likely due to the signature change making the docstring usually inapplicable.  In this case we're just doing instance-binding so these attributes remain relevant.  Simply wrapping `Partial` does not work alone as it sets the `__wrapped__` attribute, which causes inspection of the signature to think a `self` argument is still expected.

Apply functools.wraps to Module methods to preserve docstrings

---

equinox/_ad.py
equinox/_errors.py
equinox/_eval_shape.py
equinox/_jit.py
equinox/_make_jaxpr.py
equinox/_vmap_pmap.py
equinox/internal/__init__.py
equinox/internal/_debug.py
equinox/internal/_finalise_jaxpr.py

In particular this is controlled through a new `EQX_ON_ERROR=<raise|breakpoint>` environment variable.
Note that `EQX_ON_ERROR=breakpoint` sometimes runs afoul of this bug in core JAX: https://github.com/google/jax/issues/16732. If so this can be worked around by deleting intermediate `jax.jit`/`eqx.filter_jit` decorators.

error_if now has a breakpoint option

---

.gitignore
equinox/nn/_embedding.py

Hi Patrick, 
I've noticed that you could do:
```python
import jax
key = jax.random.PRNGKey(32)
emb = eqx.nn.Embedding(4, -1, key=key)
```
Normally, you wouldn't do this, because it makes not much sense, but sometimes you use some struct which holds the params for your model, and those might have negative numbers in them because - as is the case in LLaMA2 - those are set later (e.g. by the tokenizer). 
If you pass negative numbers in there, you get this error:
```
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/artur/workspace/equinox-llama2/.venv/lib/python3.10/site-packages/equinox/_module.py", line 186, in __call__
self = super(_ModuleMeta, …
```

Assertions for eqx.nn.Embedding: Sizes must not be negative

---

equinox/_tree.py

Changes error for operation on non-pytree leaves to a `TypeError`, updated the error message.

Updating error message for operation on non-pytree leaves

---

docs/api/nn/stateful.md
equinox/nn/__init__.py
equinox/nn/_batch_norm.py
equinox/nn/_composed.py
equinox/nn/_spectral_norm.py
equinox/nn/_stateful.py
tests/test_nn.py

Added the StatefulLayer as per discussion https://github.com/patrick-kidger/equinox/issues/448
One doubt I have is the `inference` parameter, it is not utilised by other norms. 
If BN needs to be easily interchangable with other norms, we might want to either remove `inference` parameter from BN and only rely on the self.inference flag or
add `inference` params to other normalisation layers as well. 
Also, do all Stateful layers utilise the `inference` flag?

first draft for BN support in nn.Sequential

---

equinox/nn/_attention.py

It seems worth documenting the convention explicitly since, unless I'm missing something, it's the opposite of e.g. [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html)'s.

Document mask convention

---

equinox/_jit.py
equinox/_vmap_pmap.py

Resolves https://github.com/patrick-kidger/equinox/issues/467.
Note that I wasn't able to run most tests because I kept getting segfaults (I assume this is because I'm on NixOS which is kind of a special snowflake and I didn't properly Nixify the project).

Fix documentation and acceptable values for `filter_pmap`'s 'donate'

---

equinox/_tree.py

Fix the name of the function in the comment, from the one that was (probably) used in older versions, to the currently existing one.
I was having an issue related to the incorrect construction of PyTree, thus was reading the source code of the implementation. Noticed that the name in the comment was incorrect.

Minor help comment fix

---

equinox/_module.py
tests/test_module.py

Support class creation kwargs, e.g. `class A(eqx.Module, foo=bar)`.

---

docs/api/module/advanced_fields.md
equinox/_module.py
tests/test_module.py

As discussed in #472, it would be nice to have a way to check invariants after a class has been instantiated. Typical use cases are something like:
```python
class A(eqx.Module):
x: int
def __check_init__(self):
if x < 0:
raise ValueError("x must be non-negative")
```
This PR adds `__check_init__`, which is automatically called after initialisation.
---
Now you may wonder, why not use `__post_init__`, as provided by dataclasses? It turns out that this use-case isn't well-served by `__post_init__`. The reason is that `__post_init__` is not called if a subclass defines an `__init__` or `__post_init__` method of its own, and forgets to call `super().__post_init__()`. Any checks placed in `__post_init__` are silently never run!
Indeed, it turns out exactly this issue has existed in Diffrax …

Added Module.__check_init__ for after-initialisation checking of invariants. See #472.

---

docs/api/nn/stateful.md
equinox/nn/__init__.py
equinox/nn/_batch_norm.py
equinox/nn/_spectral_norm.py
equinox/nn/_stateful.py
examples/stateful.ipynb
tests/test_stateful.py

This is actually a minor breaking change: the API has changed from `eqx.nn.StateIndex(callable_returning_value)` to just `eqx.nn.StateIndex(value)`. In practice creating custom stateful layers was an advanced API surface that wasn't really documented before, so I'm tempted to release this as a `v0.10.*` release, rather than bumping to `v0.11.0`.
This also updates the recommended way of creating state from `eqx.nn.State(model)` to `eqx.nn.make_with_state(model)`. This is needed to ensure memory usage behaves correctly. Nonetheless the previous `eqx.nn.State(model)`  approach will do the correct thing (other than consuming some extra memory), for backward compatibility.
This change also introduces substantially updated documentation on stateful layers, which should help usage here a lot. …

Stateful now supports vmap

---

docs/api/nn/shared.md
equinox/nn/__init__.py
equinox/nn/_shared.py
mkdocs.yml
tests/test_shared.py

Added support for sharing layers between different parts of a model.
This has the API `eqx.nn.Shared(pytree, where, get)`. At init time, then everything in `where(pytree)` is deleted -- these as the duplicate nodes we want to remove. At call time, everything in `get(pytree)` is inserted in their place -- these as the nodes we're keeping, and in doing so we restore a layer that we can evaluate.
Example usage like so:
```python
import jax.numpy as jnp
from jaxtyping import Array, Int
class LanguageModel(eqx.Module):
shared: eqx.nn.Shared
def __init__(self):
embedding = eqx.nn.Embedding(...)
linear = eqx.nn.Linear(...)
where = lambda pair: pair[1].weight
get = lambda pair: pair[0].weight
self.shared = eqx.nn.Shared((embedding, linear), where, get)
def __call__(self, …
```

Added support for sharing layers

---

equinox/_ad.py
tests/test_ad.py
tests/test_nn.py

Calling equinox.filter_{grad, value_and_grad} without a positional first argument now raises a better error message.

---

equinox/_module.py
equinox/_pretty_print.py
tests/test_module.py

Drive-by: improved pretty-printing of dataclasses with unintialised fields.

Fixed spurious error when accessing methods during __init__.

---

docs/api/module/advanced_fields.md
docs/pattern.md
equinox/_module.py
mkdocs.yml
tests/test_module.py

- Updated the text to be easier to read.
- Loosened the requirements on the pattern a little bit -- in particular
to allow abstract classes to have __init__ methods and attributes,
as long as they're the only class in the hierarchy to have them.
- Now explicitly checking that you don't subclass a concrete class, as
otherwise you could still do so, just without overriding any
methods / only adding new methods.

Updated the abstract/final design pattern.

---

.gitignore
equinox/nn/_normalisation.py
examples/vision_transformer.ipynb
mkdocs.yml

This builds on #483. The main changes here are to:
- Have two separate `LayerNorm` layers, rather than sharing weights between the two.
- Compute layer normalisation separately for each patch, rather than across every channel simultaneously.
These improve test accuracy from 76% to 79%.
Other than that:
- Added the example to `mkdocs.yml` so that it appears in the rendered docs.
- Tweaked the new LayerNorm error message to be readable. (I was hitting it when running the original implementation. Likely a bug of the form that this new error was designed to catch!)
(CC @ahmed-alllam)

Tweaked ViT example

---

equinox/_module.py
tests/test_module.py

Fixed eqx.field(metadata=...) resulting in static and converter being ignored.

---

docs/tricks.md

The [scan-over-layers example](https://docs.kidger.site/equinox/tricks/#improve-compilation-speed-with-scan-over-layers) in the tricks section of the docs currently outputs just the result of the final MLP acting on the input. Changing `mlp(x)` to `mlp(_x)` inside the scan function `f` leads to the intended behavior.

Fix scan-over-layers example in docs

---

equinox/_enum.py
equinox/_module.py
equinox/nn/_attention.py

This is mostly for simplicitly/compatibility with other libraries later down the line -- partially-stringified type annotations are a bit of a nightmare to parse.

Enumerations now use a fully-stringified type annotation.

---

equinox/debug/_announce_transform.py
equinox/internal/_loop/checkpointed.py
equinox/internal/_loop/common.py
equinox/nn/_normalisation.py
tests/test_while_loop.py

This is fairly finickity! So, the checkpointed while loop (CWL) needs
to figure out which cotangents to propagate backward. There are two
criteria for this:
(1) only some inputs actually need cotangents at all. Any parts of the
carry that are unrelated to those inputs can be skipped.
(2) some cotangents might be resolvable as symbolic zeros, and can thus
be skipped.
Previously, we handled (2) but did not handle (1). In practice this
was mostly fine. We just pretended all (inexact) inputs needed
cotangents, and let anything superfluous get DCE'd at the end.
However, this has one niche problem, which is that it is incompatible
with `eqxi.nondifferentiable` -- which is used to mark an inexact
input as nondifferentiable, and raise a trace-time error if we attempt
to differentiate it.
With …

CWL now compatible with partially nondifferentiable body functions.

---

equinox/_config.py
equinox/_errors.py
equinox/_module.py

- Now has a customisable number of frames, according to the
`EQX_ON_ERROR_BREAKPOINT_FRAMES` environment variable. This is useful
as JAX has a bug when combining certain operations with many frames
(https://github.com/google/jax/issues/16732).
- `_module.py` is now excluded tracebacks.

EQX_ON_ERROR=breakpoint improvements.

---

equinox/_ad.py

I ran into this while trying to update the RNN tutorial to use `jaxtyping`.
Using a bounded type variable conveys to the type checker that wrapping a function with `filter_value_and_grad` will not change the type of value returned by the original function.
As an example:
Suppose `f` returns a `float`. Let `wrapped = filter_value_and_grad(f)`. Then the return type of `wrapped` is `tuple[_Scalar, PyTree]`, not `tuple[float, PyTree]`, where `_Scalar` is defined here: https://github.com/patrick-kidger/equinox/blob/56bafcb17bbced52974cf8fe0ee84d20cf778e38/equinox/_ad.py#L102
The wrapped function can return a value of a different type so long as it is also a `_Scalar` (like `complex`).
Using the type variable communicates this invariant to the type checker.
I opted not to replace `_Scalar` with …

filter_value_and_grad: preserve return type of wrapped function

---

equinox/_enum.py
tests/test_enum.py

This is useful for keeping things statically resolved for as long as
possible. Even if the predicate is traced, in this scenario we don't
need to promote the output to a tracer.

Enumeration.where(tracer, x, x) is now x.

---

equinox/internal/__init__.py
equinox/internal/_loop/__init__.py
equinox/internal/_loop/common.py

This is for use as a dataclass annotation, as jaxtyping
will verify that the type is correct.
I'm not super happy with this. Buffers are getting increasingly
complicated! I suspect a better resolution will be to move Buffers into
Quax and treat them as array-ish objects, but that's fairly
complicated.

Added a MaybeBuffer annotation.

---

equinox/_compile_utils.py
equinox/_jit.py
equinox/_vmap_pmap.py
tests/test_jit.py
tests/test_pmap.py

This gives a way to exclude some arguments from donation -- pass them
through the first argument. (We did previously recommend just using
`jnp.copy`, but that's not that performant of an option, so we can do
better.)

Added filter_jit(..., donate="{all,warn}-except-first")

---

equinox/_enum.py

The link to the `Enumeration` objects was stale, linking to the old docs location. This was propagating up through `Lineax` and `Optimisitx`.

Fixing broken link to Enumueration objects

---

equinox/_module.py
tests/test_module.py

This is to support downstream libraries (e.g. typecheckers) which may
wish to monkey-patch a method.

Support setattr(module, name, function).

---

equinox/_ad.py

Hi Patrick,
I encountered incorrect error message during using ```eqx.filter_grad```:
```python
from jax import numpy as jnp, tree_util as jtu
@eqx.filter_grad
def f(a):
return jnp.sum(a)
eqx.filter_grad(jtu.Partial(f, a=jnp.ones((3,2))))()
```
Throws 
```
Functions wrapped with `equinox.filter_{grad, value and grad}` must have their 
first argument passed by position, not keyword. (This is the argument that is differentiated).
```
which does not make sense in this scenario: there are no keyword arguments!
I simply added a check for no keyword arguments, that now states that ```... there must be at least one positional argument ... ``` when no kwargs are available.

Better error message when no kwargs passed to ```filter_grad```

---

equinox/nn/_attention.py
tests/test_nn.py

resolves #553
I had the same problem as described in the issue in my own implementation. I added `softmax_dtype` as an argument.
Its type should be `jax.typing.DTypeLike`, but this type is not runtime checkable.
I made it a string for now, but I hope there is a better solution.

Mixed precision for attention

---

docs/api/nn/normalisation.md
equinox/nn/__init__.py
equinox/nn/_normalisation.py

Branched from #545 addressing reviewers' comments.

Add RMSNorm

---

equinox/nn/_normalisation.py

In the documentation with the new RMS the citation is not rendering properly
I believe this is just because the } was offset, so I changed that to match the other citations

Fix documentation bug

---

equinox/_jit.py

JAX is switching from pybind11 to nanobind, and nanobind formats this error differently, with the traceback preceding the EqxRuntimeError message. If we change the "At:" split to accept zero or more "At:" pieces, things work as intended with both versions.

Make code that parses callback errors more tolerant of message format.

---

equinox/nn/_linear.py
tests/test_nn.py

Simple addition of the dtype argument along with a very simple test (will increase the code coverage later).
A few thoughts:
1. If we don't make dtype an attribute, then we won't be able to do certain "nice to have" things in the `__call__`. For example, what if the user passed a `float32` array to a layer initialized with `float16`? Ideally we should warn the user to avoid silent bugs
2. I am not sure what should be the right annotation for the dtype argument

Simple `dtype` argument addition

---

equinox/nn/_attention.py
equinox/nn/_batch_norm.py
equinox/nn/_conv.py
equinox/nn/_embedding.py
equinox/nn/_mlp.py
equinox/nn/_normalisation.py
equinox/nn/_rnn.py
equinox/nn/_spectral_norm.py

Basically the same as #680 but for the rest of the API.
Double check `SpectralNorm` - I'm not 100% confident in that one.

Add dtypes to the rest of eqx.nn

---

equinox/internal/_loop/bounded.py
equinox/internal/_loop/common.py
equinox/internal/_nontraceable.py

This is a fix for https://github.com/patrick-kidger/optimistix/issues/48
It happens occasionally that JAX will insert a spurious vmap. It seems like we're hitting one of these cases.
In particular I found that:
- We are hitting this `nonbatchable` call https://github.com/patrick-kidger/equinox/blob/60612c13666ec75350a83972396c94fc684d223c/equinox/internal/_loop/common.py#L432, due to `step` getting batched.
- Inserting a `val = (nonbatchable(val[0]),) + val[1:]` here: https://github.com/patrick-kidger/equinox/blob/60612c13666ec75350a83972396c94fc684d223c/equinox/internal/_loop/bounded.py#L72 will also trigger an error before the previously-mentioned one. But shifting this additional check to the other side of the `jax.checkpoint` (a few lines further down) will not raise an error before …

Fix for https://github.com/patrick-kidger/optimistix/issues/48

---

equinox/_ad.py
equinox/internal/_loop/checkpointed.py
equinox/internal/_loop/common.py
tests/test_while_loop.py

The main improvement here is that a checkpointed while loop will now only propagate perturbations for those outputs that are actually perturbed. Whilst this doesn't affect the backward pass at all (we were already trimming the cotangents according to this criterion), this now means that any calls to `eqx.nondifferentiable`, or any primitive without a JVP rule, will now no longer throw an error.
In addition, this commit includes a couple of crash fixes (needed to pass the new test).
In particular this fixes the use of `TextProgressBar` reported in https://github.com/patrick-kidger/diffrax/issues/396.

Better AD for checkpointed while loop.

---

equinox/_jit.py
equinox/_module.py
equinox/internal/_noinline.py
tests/test_debug.py
tests/test_noinline.py

- callback inputs are now `Array`s rather than `array`s.
- `emit_python_callback` now uses a keyword argument for what was once a positional argument.
Other nice-to-haves whilst I'm here:
- Removed `filter_jit` passing function default arguments across the JIT boundary. In particular this is incompatible with `filter_jit(filter_vmap(eqx.nn.MLP(...)))`, as then it tries to pass the `MLP.__call__(..., *, key=...)` default argument through, but `filter_vmap` does not allow keyword arguments.
- Added some `stacklevel`s to some warnings.

Fixes for compatibility with JAX version 0.4.28.

---

equinox/_tree.py
tests/test_tree.py

See #715 and #717. CC @lockwo.

Fixed `eqx.tree_at` when used alongside an empty namedtuple.

---

tests/test_ad.py
tests/test_sharding.py

`jax.tree_map` was deprecated in JAX v0.4.26; preferred replacements are `jax.tree.map` (JAX v0.4.25 or later) or `jax.tree_util.tree_map` (any JAX version).

Avoid use of deprecated jax.tree_map

---

equinox/nn/_normalisation.py

The norm calculations should always be done with at least `fp32` dtype, and then the result should be casted back to the original dtype

Fix rmsnorm

---

.gitignore
.pre-commit-config.yaml
equinox/_ad.py
equinox/_better_abstract.py
equinox/_enum.py
equinox/_jit.py
equinox/_module.py
equinox/_vmap_pmap.py
equinox/debug/_max_traces.py
equinox/internal/_finalise_jaxpr.py
equinox/internal/_nontraceable.py
equinox/nn/_misc.py
equinox/nn/_normalisation.py
equinox/nn/_sequential.py
equinox/nn/_stateful.py
pyproject.toml
tests/test_abstract.py

I've updated the pre-commit hook's ruff version to v.0.4.4.
This also meant that the top level "lint" section in the pyproject.toml had to change as well (I think this change came after v.0.2.0).

Updated ruff

---

equinox/nn/_rnn.py

1. A typo: it should have been "self.cell"
2. A small clarification (in addition to the docstring) that the LSTM cell outputs a tuple - as opposed to the GRUCell, which outputs a single value

Update _rnn.py docs

---

equinox/nn/_embedding.py
tests/test_nn.py

It seems we forgot to make the `theta` variable public. This way, if you wanted to implement LLaMa3, you'd have a problem because they use a `theta` value of 50000.0.

Update _embedding.py RopeEmbeddings

---

equinox/_ad.py
tests/test_ad.py

I just found that jacfwd breaks if there are no static outputs from the Jacobian. E.g. it fails on the simple neural network on the home page. This fixes that (without the change, the new tests would fail, they would encounter an error because eqx.combine is call on a pytree and a None object)

Fix jacfwd

---

equinox/_module.py
tests/test_errors.py

jaxtyping v0.2.29 now wraps functions without annotations as well. That changes some tracebacks slightly.

---

equinox/_ad.py

See https://github.com/patrick-kidger/equinox/issues/745#issuecomment-2148560546.
Also improves the documentation into a larger example, to help make clear why some tangent may be `None`.

Fixes crash on symbolic zero tangents for kwargs.

---

docs/faq.md
equinox/_sharding.py
equinox/_update.py
examples/score_based_diffusion.ipynb
examples/serialisation.ipynb
examples/unet.ipynb

To catch broken links you can run this every time you do a major refactoring of the documentation.
```bash
wget --spider  -o wget.log  -e robots=off --wait 1 -r -p https://docs.kidger.site/equinox/
```
[source](https://stackoverflow.com/questions/65515/how-to-find-broken-links-on-a-website)

Broken links and how to find them

---

equinox/_misc.py
equinox/nn/_conv.py
equinox/nn/_linear.py
equinox/nn/_misc.py
equinox/nn/_rnn.py
tests/test_debug.py
tests/test_nn.py
tests/test_sharding.py

As discussed in #763, this PR adds support of complex dtypes for `Linear`, `Conv`, `GRUCell`, and `LSTMCell`.
A default initializer is defined in `eqx._misc` and called in initializations. Is it better to define it in `eqx.nn._misc`?
Some tests are added in `tests/test_nn.py` for complex dtypes and passed.
A minor problem that makes the test fail in my `jax==0.4.25` is also fixed in `tests/test_debug.py`.

Support complex dtypes in networks

---

equinox/_module.py

Addresses https://github.com/patrick-kidger/equinox/issues/782.
```python
from abc import abstractmethod
class AbstractA(eqx.Module, strict=True):
@abstractmethod
def foo(self):
pass
class B(AbstractA, strict=True):
pass
#def foo(self):
b = B()
```
old error`TypeError: Abstract strict 'eqx.Module's must be named starting with 'Abstract' or '_Abstract'. Got B when defining __main__.B.`
Now yields: 
```
TypeError: Abstract strict `eqx.Module`s must be named starting with 'Abstract' or '_Abstract'. 
Got B when defining __main__.B. For concrete moduels, B has abstract methods: ['foo'].
```

Better strict error

---

equinox/_ad.py
equinox/_module.py
equinox/_vmap_pmap.py
tests/test_module.py

Originally, by just checking the type, users could still footgun themselves with `Static` arrays if they hide them in pytrees (they still can if they use field). For example, tuple of array will still try to do this and won't error, but is actually an error since a tuple relies on the hashes of its members. 
As a solution, I figured it would be more direct to just see if it was hashable at all, but perhaps there are some edge cases where this might not be ideal(?). However, I could only do this for the `Static` directly not the field marker, since we don't access the `init` of the user so if they just type a `tuple` and mark it as static then fill it with arrays, I'm not sure how we could catch that.

Disable static arrays

---

equinox/_module.py
tests/test_module.py

Fixes cooperative multiple inheritance with `__post_init__`

---

.pre-commit-config.yaml
docs/all-of-equinox.md
docs/api/transformations.md
docs/faq.md
docs/pattern.md
equinox/_ad.py
equinox/_better_abstract.py
equinox/_callback.py
equinox/_enum.py
equinox/_errors.py
equinox/_filters.py
equinox/_make_jaxpr.py
equinox/_module.py
equinox/_serialisation.py
equinox/_tree.py
equinox/_unvmap.py
equinox/_vmap_pmap.py
equinox/debug/_backward_nan.py
equinox/debug/_dce.py
equinox/debug/_max_traces.py
equinox/internal/_getkey.py
equinox/internal/_loop/checkpointed.py
equinox/internal/_noinline.py
equinox/internal/_onnx.py
equinox/internal/_primitive.py
equinox/nn/_conv.py
equinox/nn/_pool.py
equinox/nn/_stateful.py
examples/parallelism.ipynb
examples/stateful.ipynb

Also added ```toml``` filetype to ruff scanning, since ruff has some checks for the pyproject.toml structure: [RUF200](https://docs.astral.sh/ruff/rules/invalid-pyproject-toml/)

build: bump up precommit hooks

---

equinox/nn/_embedding.py
tests/test_nn.py

RoPE embeddings use complex as an underlying representation for the frequencies, which leads to it enforcing ```float32``` dtype when applying to any float type that is lower in the promotion chain than ```float32``` (e.g. ```float16```/```bfloat16```). This PR fixes the issue by adding a new keyword argument, ```dtype```, and using the frequencies with the correct ```dtype``` throughout the implementation.

fix: RoPE embeddings do not preserve dtypes

---

.github/workflows/release.yml
.github/workflows/run_tests.yml
CONTRIBUTING.md
pyproject.toml
tests/requirements.txt

Makes it easier to set up dev env.

Add [test] and update CONTRIBUTING

---

equinox/_filters.py

In the common case wherein all trees have the same structure, the return should have the same structure.  Helps type checking a lot.

Add overloads to eqx.combine

---

equinox/nn/_stateful.py

Fixes https://github.com/patrick-kidger/equinox/issues/842

Allow StateIndex to be passed dynamically

---

.github/workflows/release.yml
equinox/_ad.py
equinox/_jit.py
equinox/internal/_primitive.py

Fixes https://github.com/patrick-kidger/diffrax/issues/508

More fixes for JAX 0.4.34

---

pyproject.toml

It is currently impossible to add equinox to a modern Python project using Poetry, because the current pyproject.toml says that it only supports Python 3.9
This PR fixes this

Allow Python versions higher than 3.9

---

equinox/_tree.py

Improves docs for `tree_at` and `tree_check`.

---

equinox/nn/_normalisation.py
tests/test_nn.py

Irrespective of the dtype passed to the normalization layers, the calculations should be done with fp32 or higher dtype. Not doing that can cause instabilities in training which is too common when someone is training models in half-precision. Now, we can delegate this to the end user to do this explicitly, but it is an easy thing to miss. This PR takes care of that.

Fix computation in normalization layers

---

equinox/_vmap_pmap.py
pyproject.toml
tests/test_pmap.py
tests/test_vmap.py

Fixes https://github.com/patrick-kidger/equinox/issues/900.

Fix filter_vmap with out_axes!=0,1 producing the wrong axis order.

---

.github/workflows/run_tests.yml
.pre-commit-config.yaml
equinox/_ad.py
equinox/_vmap_pmap.py
equinox/internal/__init__.py
equinox/internal/_loop/common.py
equinox/internal/_primitive.py
pyproject.toml
tests/test_pmap.py
tests/test_primitive.py
tests/test_vmap.py

See:
- https://github.com/jax-ml/jax/issues/25289
- https://github.com/patrick-kidger/diffrax/issues/532
The problem was that batching has now become a dynamic trace, and our batching rules were not set up to handle the case that every batch axis is `not_mapped`.

Fix breaking changes introduced in JAX 0.4.36.

---

equinox/_ad.py
equinox/_make_jaxpr.py
equinox/_unvmap.py
equinox/debug/_announce_transform.py
equinox/internal/_finalise_jaxpr.py
equinox/internal/_loop/common.py
equinox/internal/_noinline.py
equinox/internal/_nontraceable.py
equinox/internal/_primitive.py
mkdocs.yml
pyproject.toml
tests/test_finalise_jaxpr.py
tests/test_nontraceable.py
tests/test_primitive.py

Jax v0.4.38 deprecated many APIs in jax.core, and can be replaced instead by jax.extend.core.
Jax v0.4.38 also required me to upgrade python.
Fixes: https://github.com/patrick-kidger/equinox/issues/913

Upgrade jax and fix deprecation warnings

---

.pre-commit-config.yaml
equinox/_enum.py
equinox/_filters.py
equinox/internal/_onnx.py

I've realised that this only works if you have that particular version of Python installed locally -- pre-commit doesn't download this for you.
This unacceptably raises the bar for making contributions -- folks shouldn't have to modify their global system just to offer a PR against Equinox.
Unfortunately this has meant that I've had to remove a couple of dependencies from the `additional_dependencies` list, as they don't support Python 3.13, which is what is sometimes selected.
(Alternatives considered:
- Install the specified version of Python as part of the pre-commit hook. This would be ideal. Unfortunately `pre-commit` passes the specified `language_version` to `python -m virtualenv` under the hood, and that doesn't seem to offer a way to do this.
- Based on the above: something with …

Removed the requirement for a particular version of Python in pre-commit

---

README.md
docs/index.md

Resolves #929 
* Note existence of conda-forge feedstock in install instructions.
- c.f. https://github.com/conda-forge/equinox-feedstock

docs: Add conda-forge feedstock mention

---

equinox/nn/_linear.py
tests/test_nn.py

`math.sqrt(0)` throws an exception, which prevents `eqx.nn.Linear(0, 4)` from working, even though it is well defined.

Allow zero shapes in nn.Linear

---

equinox/_ad.py

Fix for warning of jnp.shape(:jax.ShapeDtypeStuct)

---

equinox/_jit.py

This is the second (and last) patch related to #973 and should hopefully be a little simpler than #976.
The idea here is that for certain wrapped methods (mainly `_JitWrapper._call`) we recompute the BoundMethod every time. This patch caches the BoundMethod.
This should be safe, as the cached entry is used if and only if the instance is the same Module and since Modules are immutable the BoundMethod is the same.
With this patch equinox is within a few tens of milliseconds of jax (will update PR later with proper numbers).

Avoid calling _wrap_method.__get__ on _JitWrapper

---

equinox/_compile_utils.py

This is just a very small change to `hashable_partition` that avoids calling `filter_fn` twice for every leaf.
On my machine this saves 200μs on the MLP example (~260 leaves).
All tests are passing and there should be no behavior change.
Old: 
```Python
%timeit -r7 -n500 fwd_eqx(dyn_flat, x).block_until_ready()
2.36 ms ± 58.1 μs per loop (mean ± std. dev. of 7 runs, 500 loops each)
```
New:
```Python
%timeit -r7 -n500 fwd_eqx(dyn_flat, x).block_until_ready()
2.16 ms ± 47 μs per loop (mean ± std. dev. of 7 runs, 500 loops each)
```

Minor optimization in hashable_partition

---

equinox/_module.py
tests/test_pformat.py

Partly addresses #961.
I don't see a benchmarking suite, e.g. using https://pypi.org/project/pytest-codspeed/, so in the attached notebook (attached as a ZIP because GH doesn't support directly attaching ipynb) I'm finding ~25% speedup towards matching the raw jax (around a 10% speedup overall).
[overhead.ipynb.zip](https://github.com/user-attachments/files/19694256/overhead.ipynb.zip)
This PR:
1. removes `_flatten_module` in favor of one defined in `_ActualModuleMeta.__new__` allowing for many aspects of the flattening to be pre-computed.
2. add slots to `_FlattenedData`, which should provide a minuscule speedup and reduction in memory use. Didn't hurt so 🤷.
3. Combined the `wrapper_field_names` and `wrapper_field_values` into a single field of `_FlattenedData` since it's only  ever used …

perf: speed up module (un)flattening

---

equinox/_module.py

1. Easier for users to access instead of a private sentinel.
2. simplifies later performance-related logic changes.
3. Broadens support to allow `dataclasses.field(metadata=dict(converter=None))`, not just `eqx.field`.
Follow up to #994.

feat: converter = None as the sentinel

---

.github/workflows/run_tests.yml
equinox/nn/_batch_norm.py
tests/test_nn.py
tests/test_serialisation.py
tests/test_stateful.py

Revives https://github.com/patrick-kidger/equinox/pull/675, but ideally a smaller/simpler change (that doesn't require any math) that matches the patterns in flax/haiku (see: https://github.com/google-deepmind/dm-haiku/blob/main/haiku/_src/batch_norm.py#L42%23L206, https://github.com/google-deepmind/dm-haiku/blob/main/haiku/_src/moving_averages.py#L41%23L139). Has some hardcoded defaults (e.g. I don't support warmup iterations at all), but should help the users of batch norm. In addition to the stability in the initial example, here is an example on an AlphaZero model playing 9x9 Go: 
This screenshot (and code) also comes from this PR: https://github.com/sotetsuk/pgx/pull/1300

Batch BatchNorm

---

equinox/nn/_sequential.py

This PR just adds a short sentence, clarifying that `Lambda.fn` is treated as a node of the PyTree. The behavior seemed surprising to me at first.

Clarify Lambda.fn behavior in PyTrees

---

.github/workflows/run_tests.yml
equinox/_module.py
tests/test_module.py

Closes #1016.
In the end, there were two issues: (1) `DocTestFinder._from_module` was returning `False` because the `__module__` attribute was not correct, and (2) the documentation was not copied to the wrapper class so doctests could not be discovered.
My solution is inspired from what Python is doing with their own decorators, see https://github.com/python/cpython/blob/4617d68d73409e83d6ab31106d10421d44048787/Lib/functools.py#L1033-L1049

fix(lib): allow DocTest to discover methods from subclasses `Module`

---

equinox/_filters.py

Add a more explicit error message when non static leaf values are passed to filter_spec #1036

add check for regular values at filter_spec leaves

---

equinox/nn/_stateful.py

See #1050.
With this change
```python
class StatefulModule(eqx.Module):
counter_index: eqx.nn.StateIndex
def __init__(self):
counter_init = 0
self.counter_index = eqx.nn.StateIndex(counter_init)
def __call__(self, x, state):
counter = state.get(self.counter_index)
counter = counter + 1
state = state.set(self.counter_index, counter)
return x, state
class TopModule(eqx.Module):
stateful_mod: eqx.Module
def __init__(self):
self.stateful_mod = StatefulModule()
def __call__(self, x, state):
return self.stateful_mod(x, state)
proc, state = eqx.nn.make_with_state(TopModule)()
state, state._state, state.get(proc.stateful_mod.counter_index)
```
prints
```
(State(TopModule.stateful_mod.counter_index=weak_i32[]), {'TopModule.stateful_mod.counter_index': Array(0, dtype=int32, …
```

use keypaths instead of ints for state keys

---

docs/awesome-list.md

So I made this library (Currently at its very early stages!) that allows you to write this:
```python
class AffineMap(TypedModule):
k: Float[Array, "n m"]
b: Float[Array, "n"]
def __call__(self: Self, x: Float[Array, "m"]) -> Float[Array, "n"]:
return jnp.dot(self.k, x) + self.b
f = AffineMap(k=jnp.ones((3, 2), dtype=float), b=jnp.zeros(3))
f(jnp.array([1., 2.]))
```
The initializer and member methods will automatically type-check at runtime.

Shameless plug: add typinox to awesome-list
